### ISSUE TITLE
Do not write data about devices states in config.json on each change to prevent flash problems on RPi.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#231]
May be do not store changes of all devices metrics except for title?

Neils, same for your history - we need to keep it in memory and save only hourly

**Comment by ronie-z-wave** [comment]
Sry I don't get the context ... Are you talking about the events/notivications that are thrown by the module InbandNotificatons (old: DeviceMonitor) or only about the history?

**Comment by PoltoS** [comment]
yes, about event log.

same needs to be done in future for config.json - too many people are affected by RPi problem with loss of config.json

**Comment by ronie-z-wave** [comment]
I've thought a little bit about that issue ... e.g. event log:
maybe one way to do this in AC - addNotification()
- store every device notification in array and concat this with notifications hourly ...

but then we have no live data and need new api to read data from ram ... 
oor maybe we have to try some database solutions to handle this in future?

**Comment by pz1** [comment]
fwiw: Or use a small ramdrive with hourly backup?

**Comment by aivs** [comment]
Good idea.
May be after z-way start poll all devices to get actual state?

**Comment by ronie-z-wave** [comment]
ok, ramdrive looks like a nice alternative ... so I store the changes in a temporary file on e.g. /mnt/temp - add this directory to /etc/fstab - and then I'll create a symlink from this file to store, save/read from it with save/loadObject() ... and finally I poll the changes hourly to notification.js and delete the content of the file ... and so on ...

**Comment by ronie-z-wave** [comment]
btw: could this work or does it need more 'magic'?

**Comment by pz1** [comment]
While you are at it, you may consider to also write the logfile to ramdrive. Log file is hammering quite heavily on the SD card (I did a short trial with the syslog server on my NAS, which missed a lot of records from the z-way-server.log, especially at start-up. A ramdrive for that is on my todo list since a week.)

**Comment by ronie-z-wave** [comment]
So for testing I've added the execution of this shell to rc.local:
![ramdir](https://cloud.githubusercontent.com/assets/10545480/7182890/6b6a5b8c-e454-11e4-9265-670017a4892a.PNG)

- only workaround because I had some problems to mount this directory automatically by adding to /etc/fstab ... 

but now I need some functions/API to read/write in this storage - so how can I do this? Maybe someone can guide me through z-way underground :)

**Comment by PoltoS** [comment]
Make a symlink to the file in ram.

@pz1 For log file we suggest to use syslog - it store it in memory.
