### ISSUE TITLE
Generate widgets for CentralScene based on maxScenes number.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/home-automation#286]
May be add something like this (around line 1796)?
Just fix it to have supportSwitchController in the scope of these lines.

Please talk with CP - he did not wanted to generate all buttons, but only based on individual approach to every device (via postfix).

```
                    }
```
-                } else if (this.CC["CentralScene"] === commandClassId) {
-                        var maxScenes = self.zway.devices[nodeId].instances[instanceId].commandClass[commandClassId].data.maxScenes.value;
-                        if (maxScenes) {  
-                                supportSwitchController(91, maxScenes, 'S');
-                        }
              } else if (this.CC["Battery"] === commandClassId && !self.controller.devices.get(vDevId)) {

**Comment by christianpaetz** [comment]
CentralScene reports max number of Scenes. After thinking  a bit about this. The best solution is to show all scene numbers as elements on default and limit the number with postfix. With this  we make sure that all devices work out of the bug but may generate too many widgets we can fix case by case if needed (e.g. for KFOB 4 instead of 8).

**Comment by PoltoS** [comment]
added in 2016
