### ISSUE TITLE
Firmware Update Issue (UI Related)

### ISSUE THREAD

**Issue by Irrelon** [Z-Wave-Me/home-automation#306]
Hi folks,

On version 2.2.0 when going to Management -> Firmware Update -> Update to Latest, the dialog that opens expects your server allow access on port 8084. If you are accessing this from your internal network domain or via the internal server IP (192.168.x.x) then it will work but if you are accessing from external IP and use port forwarding you only open port 8083 then it will not work.

Is port 8084 required here? I would imagine that is should be relatively simple to operate on a single port.

**Comment by PoltoS** [comment]
Well, updating the s/w from itself is a danger. And double danger to do it remotelly!

So:
1) we intentionally don't do this possible from remote, since during update you can completelly loose your box and will need to get local access anyway.
2) for security reasons we do restrict fs access (read and write) from the engine, so updating itself is just not possible. For this we have 8084 port (and it was made even more secure in v2.2.1).

So, we close thos a "wont fix". Hope you understand our arguments.

**Comment by Irrelon** [comment]
Thanks for explaining the reason why it is running on a separate port. Makes sense :+1:
