### ISSUE TITLE
Sensor polling app cannot be added in 2.2.2

### ISSUE THREAD

**Issue by alexeyzimarev** [Z-Wave-Me/home-automation#350]
I am trying to add the Sensor Polling app, can see two issues:
1) when I change the polling interval from 1 hour to something else, the field gets red border, like it is an error
2) no matter what polling interval I choose, when I click "Add", I get a message "Something went wrong". In the "events" tab there are no errors.
The app is therefore not added.

**Comment by ronie-z-wave** [comment]
Hi, 
Did you check if it is already running? Maybe you need to set Menu>My Settings>Expert View to true ...
If yes, this will be the reason the error occurs - indeed not user friendly enough, we'll work on that.

Usually this app is running by default.

**Comment by Wikibear** [comment]
This issue is always open.

- Issue is via Firefox and via Chrome.
- Checkbox ist checked
- happend with other apps also e.g. cron, Battery polling, ...
- Error: Something went wrong or Unable to update data
- Log: [I] [core] WARNING: Module 10 is a singleton and already has been instantiated. Skipping.
- Investigate javascript: "NetworkError: 500 Internal Server Error - http://192.168.1.5:8083/ZAutomation/api/v1/instances"
- Put this url into browser get positive feedback with json array
- Json via Post for Sensor Polling App: 
`{"instanceId":"0","moduleId":"SensorsPolling","active":"true","title":"Periodical Sensor Polling","params"
:{"pollDevsWithBatteries":true,"period":"60","devices":[],"devicesWithBattery":[]}}`

other erro via cron activate and deactivate:

- "NetworkError: 500 Internal Server Error - http://192.168.179.65:8083/ZAutomation/api/v1/instances"
- `---------- ERROR: ----------
e/<()build.js (Zeile 7574)
this.logError()build.js (Zeile 12723)
.responseError()build.js (Zeile 11116)
De/e/l.promise.then/w()build.js (Zeile 7583)
De/e/l.promise.then/w()build.js (Zeile 7583)
De/e/l.promise.then/w()build.js (Zeile 7583)
De/h/<.then/<()build.js (Zeile 7584)
Yd/this.$get</h.prototype.$eval()build.js (Zeile 7595)
Yd/this.$get</h.prototype.$digest()build.js (Zeile 7592)
Yd/this.$get</h.prototype.$apply()build.js (Zeile 7595)
m()build.js (Zeile 7554)
w()build.js (Zeile 7559)
ye/</B.onreadystatechange()build.js (Zeile 7561)
[Object { data={...},  status=500,  config={...},  mehr...}]
	

...;return function(){b&&c.apply(a,arguments)}}()}}]}function ka(b,a){if("__defineG...`

z way version: 2.2.2-rc3

**Comment by Wikibear** [comment]
Sorry but i have still this error:

![unbenannt](https://cloud.githubusercontent.com/assets/18314278/16725129/2944bec6-4756-11e6-8ca1-888c3844cb93.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/18314278/16725128/29436760-4756-11e6-9dda-09ade2dc2916.PNG)

**Comment by ronie-z-wave** [comment]
Ok, thx.

So I need more input. 

- Which browser do you use?
- From which version did you update to v2.2.3-rc3? 
- Which RPi model do you use? 
- Do you have a RaZberry or UZB?

Btw. what happens after restart? Still the same behaviour?

**Comment by Wikibear** [comment]
- Chrome and Firefox as described 
- v2.2.2 -> v2.2.2-rc3 -> v2.2.2-rc3
- raspi 3
- RaZberry

After upgrade i reboot hole system completely but nothing change on this issue.

**Comment by ronie-z-wave** [comment]
OK.

Hmm because it works on my side with different RPi models and also doing the update with different origin versions (v2.2.1 / v2.2.2 /v2.2.3-rc*) let's do step by step to figure out whats wrong (these steps define as it usually should be):

1. **Periodical Sensor Polling** is **not** in **Active Apps** list
-> you should be able to add it via **Local Apps**
2. Periodical Sensor Polling is in **Active Apps** list - doesn't matter if it is in-/active
-> you'll get an error message if you wan't to add a new one via **Local Apps**
-> thats what we need to enhance on our side
3. Configure an in-/active app via **Active Apps**
-> should work without error message
4. remove app **Periodical Sensor Polling** from **Active Apps** list
-> you should be able to add it via **Local Apps** again

Please give me feedback what excactly doesn't work.

**Comment by Wikibear** [comment]
OK, i think that is the problem... maybe solved:

 Periodical Sensor Polling is not in Active Apps list -> you should be able to add it via Local Apps 

PSP is in active list and i can't it again. Seems been logic. But the "Something went wrong", say me that Something is not ok. Is it not better that the user get a feedback like "App is installed"?

So i turn in circles and get active apps out of my eyes.

**Comment by ronie-z-wave** [comment]
Indeed your right.

> fyi: 
[I] [core] WARNING: Module 10 is a singleton and already has been instantiated. Skipping.
This isn't more like a bad handled backend feedback. Some of the modules like Cron, SensorsPolling, BatteryPolling etc. are defined as singleton, which means they could have only one active/incative instance in Active Apps. So the message says - "Its already added."
At the moment we work on that and we'll try to integrate it to the next release.

I'm optimistic, that this will be solved till next release ;)

**Comment by Wikibear** [comment]
Thanks for your help!

**Comment by ronie-z-wave** [comment]
fixed long time ago - singleton apps can now only be added once.
