### ISSUE TITLE
updateBackendConfig.js: Cannot start z-way-server 

### ISSUE THREAD

**Issue by sja** [Z-Wave-Me/home-automation#383]
I suddenly cannot start z-way-server. The log mentions an error at `updateBackendConfig.js:4:16` where config.json is loaded. But that file is correct JSON.

I tried updating from 2.2.3 to 2.2.4-rc20 but no success. I think, the file `automation/defaultConfigs/config.json` hasnt changed since v2.2.3.

```
[2016-10-06 16:01:28.521] [I] [core] Executing script: /*** Z-Way Home Automation Engine main executable ***************************** ...
[2016-10-06 16:01:28.524] [I] [core] Executing script: // Comon utilities and functions ...
[2016-10-06 16:01:28.533] [I] [core] Executing script: // This script transforms old formats to new ...
[2016-10-06 16:01:28.576] [E] [core] result: Error: SyntaxError: Unexpected end of input
    at automation/updateBackendConfig.js:4:16
    at automation/updateBackendConfig.js:440:3
    at automation/main.js:23:1
[2016-10-06 16:01:28.581] [E] [core] result: Error: Error: Uncaught SyntaxError: Unexpected end of input
    at Error (native)
    at automation/main.js:23:1
```

Content of automation folder:
```
root@zway:/opt/z-way-server# ll automation/ automation/userModules/
automation/:
total 368K
-rw-rw-r--  1 pi   pi   128K Jul 12 17:19 apiary.apib
-rw-rw-r--  1 pi   pi    31K Jul 12 17:19 CHANGELOG.md
drwxrwxr-x  2 pi   pi   4.0K Jul 12 17:19 classes
drwxrwxr-x  2 pi   pi   4.0K Jul 12 17:19 core
drwxrwxr-x  2 pi   pi   4.0K Jul 12 17:19 defaultConfigs
-rw-rw-r--  1 pi   pi    126 Jul 12 17:19 .gitignore
-rw-rw-r--  1 pi   pi   1.9K Jul 12 17:19 .jscsrc
-rw-rw-r--  1 pi   pi    362 Jul 12 17:19 .jshintrc
drwxrwxr-x  2 pi   pi   4.0K Jul 12 17:19 lang
drwxrwxr-x  2 pi   pi   4.0K Jul 12 17:19 lib
-rw-rw-r--  1 pi   pi   4.8K Jul 12 17:19 main.js
drwxrwxr-x 55 pi   pi   4.0K Jul 12 17:19 modules
-rw-rw-r--  1 pi   pi   7.0K Jul 12 17:19 modulesCategories.json
-rw-rw-r--  1 pi   pi    751 Jul 12 17:19 package.json
-rw-rw-r--  1 pi   pi    711 Jul 12 17:19 README.md
-rw-rw-r--  1 pi   pi   3.2K Jul 12 17:19 router.js
drwxr-xr-x  2 root root 4.0K Oct  2 18:01 storage
-rw-rw-r--  1 pi   pi   5.1K Jul 12 17:19 StorageProvider.js
-rw-rw-r--  1 pi   pi      0 Jul 12 17:19 .syscommands
drwxrwxr-x  4 pi   pi   4.0K Jul 12 17:19 __tests__
-rw-rw-r--  1 pi   pi    14K Jul 12 17:19 updateBackendConfig.js
drwxr-xr-x  6 root root 4.0K Aug  6 14:10 userModules
-rw-rw-r--  1 pi   pi   2.4K Jul 12 17:19 Utils.js
-rw-rw-r--  1 pi   pi   1.8K Jul 12 17:19 Webserver.js
-rw-rw-r--  1 pi   pi   8.8K Jul 12 17:19 WebserverRequestRouter.js
-rw-rw-r--  1 pi   pi    87K Jul 12 17:19 ZAutomationAPIProvider.js

automation/userModules/:
total 16K
drwxr-xr-x 4 root root 4.0K Jul 19 15:26 BaseModule
drwxr-xr-x 4 root root 4.0K Jul 19 15:26 HomeKitGate
drwxr-xr-x 4 root root 4.0K Jul 19 15:26 InfluxDbStats
-rw-r--r-- 1 root root    0 Jul 19 15:26 .keep
drwxr-xr-x 5 root root 4.0K Aug  6 14:10 MQTT
root@zway:/opt/z-way-server# 
```

**Comment by ronie-z-wave** [comment]
please check automation/storage directory for configjson-*.json

**Comment by sja** [comment]
Bingo! That file ends here:

```
        {
            "instanceId": "0",
            "moduleId": "MQTT",
            "active": "true",
            "title": "MQTT",
            "params": {
                "clientId": "zway",
                "host": "nas",
                "port": "1883",
                "topicPrefix": "zway",
                "topicPostfixStatus": "status",
                "topicPostfixSet": "set",
                "publications": [
                    {
                        "type": "single",
                        "deviceId": "ZWayVDev_zway_4-3-37",
                        "topic": "%roomName%/lichtSchraenke",
                        "retained": true
                    },
                    {
                        "type": "single",
                        "deviceId": "ZWayVDev_zway_28-4-49-1",
                        "topic": "%roomName%/getraenke",
                        "retained": true
                    },
                    {
                        "type": "tag",
                        "tags": [
                            "mqtt"
                        ],
                        "topic": "%roomName%/%deviceName%",
                        "retained
```

The parent of that is `"instances"`. I deleted that MQTT node and ist starts again.

**Comment by victoryred** [comment]
Hi ronie-z-wave,

I had the same problem. I performed your suggestion of please check automation/storage directory for configjson-*.json and the json file looks to be ok. Is there a way to force the system to rebuild the configjson-*.json from scratch?

**Comment by ronie-z-wave** [comment]
Hi,

you can use automation/defaultConfigs/config.json - thats the default one for you box. (The other ones have different configurations for other box types) 

1. Stop z-way-server
`$ sudo /etc/init.d/z-way-server stop`
2. change owner and group of storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json
`$ sudo chown pi:pi /opt/z-way-server/automation/storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json`
OR open in editor of your choice (vi, vim, nano) with sudo and change it directly :)
3. Edit storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json and copy the content of this file and put it into automation/storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json
4. save it and start z-way-server
`$ sudo /etc/init.d/z-way-server start`

**Comment by victoryred** [comment]
This problem is peculiar. 

It seems as though in both main.js and updateBackendConfig.js can't find the config.json file.





The following is a code snippet from updateBackendConfig.js...............



try {

 config = loadObject("config.json"); <<--- can't find the file

 } catch (ex) {

 console.log("updateBackendConfig.js- Error loading config.json:", ex.message);

}




This is the z-way-server.log file snippet........



[2016-12-15 14:09:20.916] [I] [core] Executing script: /*** Main.js, Z-Way Home Automation Engine main executable ***************************** ...

[2016-12-15 14:09:20.919] [I] [core] Executing script: // Utils.js, Common utilities and functions ...

[2016-12-15 14:09:20.935] [I] [core] Executing script: // updateBackendConfig.js, This script transforms old formats to new ...

[2016-12-15 14:09:20.947] [I] [core] updateBackendConfig.js- Error loading config.json: Unexpected token L

[2016-12-15 14:09:20.953] [I] [core] Main.js- Error loading config.json, files.json or schema.json: Unexpected token L

[2016-12-15 14:09:20.953] [I] [core] Main.js- Can't read config.json or it's broken.

[2016-12-15 14:09:20.953] [I] [core] ZAutomation engine not started.

 

However, the exception message is  "Unexpected token L" not "file not found". I say that because I can't find a json error with the config.json file so I renamed the config.json file to foo.json and the loadObject() function doesn't assert a "file not found" error.

This code snippet worked without error
try { config = loadObject("/opt/z-way-server/automation/defaultConfigs/config.json"); <<-- works correctly

 } catch (ex) {

 console.log("updateBackendConfig.js- Error loading config.json:", ex.message);

}

Thank you for your help.

Sent from iCloud


On Dec 14, 2016, at 11:11 PM, ronie-z-wave <notifications@github.com> wrote:






Hi,

you can use automation/defaultConfigs/config.json - thats the default one for you box. (The other ones have different configurations for other box types)
Stop z-way-server
$ sudo /etc/init.d/z-way-server stop
change owner and group of storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json
$ sudo chown pi:pi /opt/z-way-server/automation/storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json
 OR open in editor of your choice (vi, vim, nano) with sudo and change it directly :)
Edit storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json and copy the content of this file and put it into automation/storage/configjson-06b2d3b23dce96e1619d2b53d6c947ec.json
save it and start z-way-server
$ sudo /etc/init.d/z-way-server start

**Comment by ronie-z-wave** [comment]
Hmm ok please let me try to understand and clearify it a bit:

> loadObject(object name) and saveObject(object name, object)
Loads and saves JSON object from/to storage. These functions implements 
at storage for
application with access to the object by it's name. No folders are available.
Data is saved in automation/storage folder. Filenames are made from object names by
stripping characters but [a-ZA-Z0-9] and adding checksum from original name (to avoid name
con
icts).

Thats the official definition taken from [Z-Way Dev Manual](https://github.com/Z-Wave-Me/Z-Way-Manual/raw/master/zwayDev.pdf)

Means loadObject() works only within automation/storage folder. Unfortunately the fact, if a file that isn't found will return **null** as result, is missing in definition.

your case works because **config** is **null**, what isn't catched - no error.

```
try { config = loadObject("/opt/z-way-server/automation/defaultConfigs/config.json"); <<-- works correctly

 } catch (ex) {

 console.log("updateBackendConfig.js- Error loading config.json:", ex.message);

}
```

For me the problem seems to be in your configjson-*.json. 

updateBackendConfig.js- Error loading config.json: **Unexpected token L**  -> this sounds more like a JSON syntax problem that occurs during parsing it.

Did you also try to check it with [http://jsonlint.com/](http://jsonlint.com/) or an inbuilt JSON lint tool in your IDE (hope you don't use simple notepad :) )? 

I know from experience that finding such errors without technical help could be very difficult and frustrating.

**Comment by victoryred** [comment]
I thank you very much for your support.





The problem was indeed in the config-*.json file. I ran http://jsonlint.com/ on the file and it had issues. I decided to try a backup copy of the file and that worked. I now need to see what's changed but the system is up and running.





Thanks again for your help


 

Sent from iCloud


On Dec 15, 2016, at 11:25 PM, ronie-z-wave <notifications@github.com> wrote:






Hmm ok please let me try to understand and clearify it a bit:


loadObject(object name) and saveObject(object name, object)
 Loads and saves JSON object from/to storage. These functions implements
 at storage for
 application with access to the object by it's name. No folders are available.
 Data is saved in automation/storage folder. Filenames are made from object names by
 stripping characters but [a-ZA-Z0-9] and adding checksum from original name (to avoid name
 con
 icts).

Thats the official definition taken from Z-Way Dev Manual

Means loadObject() works only within automation/storage folder. Unfortunately the fact, if a file that isn't found will return null as result, is missing in definition.

your case works because config is null, what isn't catched - no error.
try { config = loadObject("/opt/z-way-server/automation/defaultConfigs/config.json"); <<-- works correctly

 } catch (ex) {

 console.log("updateBackendConfig.js- Error loading config.json:", ex.message);

}


For me the problem seems to be in your configjson-*.json.

updateBackendConfig.js- Error loading config.json: Unexpected token L -> this sounds more like a JSON syntax problem that occurs during parsing it.

Did you also try to check it with http://jsonlint.com/ or an inbuilt JSON lint tool in your IDE (hope you don't use simple notepad :) )?

I know from experience that finding such errors without technical help could be very difficult and frustrating.
