### ISSUE TITLE
ZMEFirmwareUpgrade - check bootloader adressing

### ISSUE THREAD

**Issue by ronie-z-wave** [Z-Wave-Me/home-automation#424]
Seems that update from 5.04 + is broken on RaZ 2

fw >= 5.04 adressing seems to be wrong, should be 0x20000?

> The problem in adressing
We need to use 0x20000 instead of 0x7800 for 05.04 - Alexander Polyakov

**Comment by PoltoS** [comment]
It depends on bootloader. There is a code addressing this: https://github.com/Z-Wave-Me/home-automation/blob/master/modules/ZWave/index.js#L1203

The problem is that we can not distinguish default bootloader (from factory) - new one or old one - both looks same. So, bootloader upgrade solves the problem.

I'm waiting this: https://github.com/Z-Wave-Me/ExpertUI/issues/244 (discussed with Marcel previously) to finally solve this problem.

**Comment by ronie-z-wave** [comment]
Ok makes sence, implementation should be done quickly :)
